# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-25 10:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dbconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=16)),
                ('port', models.CharField(max_length=5)),
                ('env', models.CharField(blank=True, choices=[('1', '\u751f\u4ea7'), ('2', '\u6d4b\u8bd5')], max_length=1, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InceptSql',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u5b57')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('note', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8')),
                ('commiter', models.CharField(max_length=20)),
                ('sqlcontent', models.TextField(blank=True, null=True)),
                ('env', models.CharField(max_length=6)),
                ('dbname', models.CharField(max_length=50)),
                ('treater', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(-3, '\u5df2\u56de\u6eda'), (-2, '\u5df2\u6682\u505c'), (-1, '\u5f85\u6267\u884c'), (0, '\u5df2\u6267\u884c'), (1, '\u5df2\u653e\u5f03'), (2, '\u6267\u884c\u5931\u8d25')], default=-1)),
                ('executerz', models.CharField(max_length=200)),
                ('exe_affected_rows', models.CharField(max_length=10)),
                ('roll_affected_rows', models.CharField(max_length=10)),
                ('rollbackopid', models.TextField(blank=True, null=True)),
                ('rollbackdb', models.CharField(max_length=100)),
                ('sqlusers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
